### ISSUE TITLE
Números mágicos

### ISSUE THREAD

**Issue by edjus** [germanlahitte/trabajoPractico2#6]
Existen números mágicos que se usan para el daño de un arma y para la vida de las piezas.
Corregir ésto, hay dos soluciones posibles:
- Constantes dentro de la clase:
```
   private final int DANIO = 10;
   public ArmaSoldado() {
        super(DANIO, Rango.cercano());
    }
```
- Tener una clase estática, con todos las constantes juntas:
```
public static class ProveedorConstantes(){
   public static int DANIO_ARMA_SOLADO = 10;
   public static int DANIO_ARMA_JINETE = 10;
   public static int VIDA_SOLDADO = 100;
   ...
}
```
De la segunda manera es más fácil configurar las constantes del juego.

**Comment by MartinDabat** [comment]
@edjus Pregunta, para la "compra" de piezas es mejor que consultemos también a esta constante?

**Comment by edjus** [comment]
@MartinDabat Sí, todo lo que sea configurable debería ir en una constante. Básicamente todos los valores del enunciado, así al corregir podemos tocar esas constantes y verificar algunas funcionalidades más rápido.

**Comment by MartinDabat** [comment]
El valor de la pieza, está en una constante de cada clase. 
La pregunta era si querías que llevemos todas las contantes (al menos las relacionadas con las piezas/armas) a una clase aparte que tenga todas las constantes. O sea el ejemplo 2 que diste.

**Comment by edjus** [comment]
Doy por cerrada la issue, pero con una sugerencia en el nombre de la clase en lugar **FactoryConstantes**, puede ser remplazado por **ProveedorConstantes** ya que el nombre Factory implica que estás creando constantes para los cuales necesitas ciertos parámetros pero no es el caso.

**Comment by germanlahitte** [comment]
Hola Edson, gracias. Consulta: codacy sugiere que no haya mayúsculas en los
paquetes, eso lo cambiamos también?

Lo que tenemos que entregar el jueves lo estamos debatiendo todavía, pero
en el branch entrega21 hay una versión completa funcionando igualmente.
Si nos ponemos de acuerdo antes lo mergeamos a master, si no te consultamos
todo el jueves.

**Comment by edjus** [comment]
Si codacy lo marca hay que corregirlo para que pase, si no debe haber alguna manera de desactivar esa validación.

Sobre la entrega me parece bien. No sé olviden de actualizar el informe hasta ahora está vacío. El informe es importante  porque facilita la corrección se espera que aparezcan justificaciones del  por qué tomaron ciertas decisiones de modelado además de si probaron otras ideas.
